// 用户模块 hook 统一导出
export { useLogin } from './useLogin'
export { useRegister } from './useRegister'
export { useGetUserProfile } from './useGetUserProfile'
export { useUpdateUserProfile } from './useUpdateUserProfile'
export { useUpdatePassword } from './useUpdatePassword'
export type { LoginPayload, LoginResPayload } from './useLogin'
export type { RegisterPayload, RegisterResPayload } from './useRegister'
export type { GetUserProfileResPayload } from './useGetUserProfile'
export type { UpdateUserProfilePayload, UpdateUserProfileResPayload } from './useUpdateUserProfile'
export type { UpdatePasswordPayload, UpdatePasswordResPayload } from './useUpdatePassword'
