/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HomeFooter: typeof import('./src/components/MusicHome/HomeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/MusicHome/HomeHeader.vue')['default']
    HotPlaylist: typeof import('./src/components/PlaylistHot/HotPlaylist.vue')['default']
    MusicFooter: typeof import('./src/components/App/MusicFooter.vue')['default']
    MusicHeader: typeof import('./src/components/App/MusicHeader.vue')['default']
    MusicListCards: typeof import('./src/components/MusicRecommend/MusicListCards.vue')['default']
    MusicRecommendCard: typeof import('./src/components/MusicRecommend/MusicRecommendCard.vue')['default']
    MvCard: typeof import('./src/components/MvRecommend/MvCard.vue')['default']
    MvListCard: typeof import('./src/components/MvRecommend/MvListCard.vue')['default']
    MvListCards: typeof import('./src/components/MvRecommend/MvListCards.vue')['default']
    PlaylistCard: typeof import('./src/components/PlaylistHot/PlaylistCard.vue')['default']
    PlaylistDots: typeof import('./src/components/PlaylistHot/PlaylistDots.vue')['default']
    PlaylistHot: typeof import('./src/components/PlaylistHot/PlaylistHot.vue')['default']
    PlaylistNav: typeof import('./src/components/PlaylistHot/PlaylistNav.vue')['default']
    PlaylistSpot: typeof import('./src/components/PlaylistHot/PlaylistSpot.vue')['default']
    RecommendMusic: typeof import('./src/components/MusicRecommend/RecommendMusic.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongCard: typeof import('./src/components/MusicRecommend/SongCard.vue')['default']
  }
}
