export const loginPath = '/auth/login'
export const registerPath = '/auth/register'
export const songsPath = '/songs'
export const playlistsPath = '/playlists'
export const actionToSongsPath = '/playlists/{id}/songs'
export const userInfoPath = '/user/profile'
export const userHistoryPath = '/user/history'
export const searchPath = '/search'
